### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chaixshot** [coalaura/vs-fivem#10]
- Issue Type: `Performance`
- Extension Name: `vs-fivem`
- Extension Version: `2.0.18`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.92.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/chai5/AppData/Local/Temp/coalaura.vs-fivem-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by coalaura** [comment]
It reads all lua files in your workspace when opened which will cause your CPU to spike until its done. This more or less time depending on the amount of files and your CPU performance. Other than that it should be relatively performant but things like diagnostics will take more and more time the bigger the file gets.

PS: The filepath you put is local to your machine, only you can access that :)
