### ISSUE TITLE
Performance on LUA GLM

### ISSUE THREAD

**Issue by chaixshot** [coalaura/vs-fivem#11]
![image](https://github.com/user-attachments/assets/a265e15c-6938-4527-8116-f1609108912e)

I noticed if LUA GLM is enable it impact huge editor performance on file 2000++ i test.
For example, slow saving file.

**Comment by coalaura** [comment]
yes, this happens cause there is no lua-glm parser in javascript at the moment. I transform the code to regular lua which is resource intensive the bigger the file gets. Transforming and then parsing a 2k+ line will use a lot of resources, sadly not something i can fix
