### ISSUE TITLE
Bad replace for "Wait"

### ISSUE THREAD

**Issue by RocwoDev** [coalaura/vs-fivem#2]
Exemple : 
I write : Wait(50)
Warning : Use Citizen.Wait instead of just Wait.
I click on Quick fix : Citizen.Wait
The (50) disapear

**Comment by coalaura** [comment]
This should be fixed now

**Comment by RocwoDev** [comment]
Nice !

Just to clarify: GTA V's Native Wait will put the script it's called from to sleep for the allotted time.
Citizen.Wait will put the current Thread to sleep.
In lua, when you call Wait, it doesn't call Native Wait. In fact, in lua, Wait is a shortcut to Citizen.Wait (line 135: [scheduler.lua](https://github.com/citizenfx/fivem/blob/master/data/shared/citizen/scripting/lua/scheduler.lua) ).
