### ISSUE TITLE
== generate warning

### ISSUE THREAD

**Issue by RocwoDev** [coalaura/vs-fivem#3]
![image](https://github.com/coalaura/vs-fivem/assets/61157993/1025b87e-de01-432f-afbb-45c8fda6b21a)

**Comment by coalaura** [comment]
Doesn't show a warning for me, are you on the latest version? Can you send a screenshot of your vs-fivem settings?

![yes](https://i.shrt.day/I8S98ULY40.webp)

**Comment by RocwoDev** [comment]
![image](https://github.com/coalaura/vs-fivem/assets/61157993/7ae96a14-c2ff-496c-b563-fb5396754c06)
Try to write this exact code :
```lua
AddEventHandler('NewPlayer', function()
    local source = source
    
    -- Hardcap things
end)
```

The comment seems to generate the problem

**Comment by coalaura** [comment]
Ah i think i know what the error is

**Comment by coalaura** [comment]
I've fixed it (not yet published), but i'd recommend doing something like:

```lua
local _source = source
-- or
local src = source
```

instead of

```lua
local source = source
```

to avoid confusion as to where which variable it referenced.

**Comment by RocwoDev** [comment]
Yes, it's good practice to change the name of the "source" variable to "src" or "_source", because if you forget the "local" keyword, then if another event is triggered while you're using this global variable, it will change.

Thank you for your hard work on this extension, it's clearly the best extension (by far) for developing in lua under FiveM, coupled with sumneko lua language server it really lets you go far in development and that's why I'm contributing as much as I can via the issues ^^

**Comment by coalaura** [comment]
Thank you very much for the kind words :D  
I appreciate you reporting these bugs!
