### ISSUE TITLE
No preview for joaat

### ISSUE THREAD

**Issue by RocwoDev** [coalaura/vs-fivem#4]
In FiveM Lua there is a joaat function, it can be good to have the jenkins hash preview on this function too

**Comment by coalaura** [comment]
works for me

![yes](https://i.shrt.day/BVT3O67TYT.webp)

**Comment by coalaura** [comment]
do you have an example code snippet where its not working?

**Comment by RocwoDev** [comment]
It actually works, I must have misplaced my mouse. 😊

**Comment by coalaura** [comment]
bet
