### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by userMacieG** [coalaura/vs-fivem#9]
You could add checks for old natives that should be replaced.
You can find some here: https://manason.github.io/effective-fivem-lua/natives/

Also my personal opinion: you should use "" only for strings that are text, otherwise ''
So for example:
```lua
RegisterNetEvent('resource:client:event', function()
    print("Hello world!")
end)

local value = 'submit'

function action()
    if value == 'submit' then
        print("Submitted")
    end
end
````

**Comment by coalaura** [comment]
I always check for those. I believe code looks cleaner and less confusing when using Citizen.Wait instead of Wait and when using AddEventHandler.

**Comment by coalaura** [comment]
And mixing single quotes and double quotes makes no sense

**Comment by coalaura** [comment]
and your pull requests are all more personal preference so i declined them

**Comment by userMacieG** [comment]
`when using AddEventHandler.` it doesnt make any sense to trigger AddEventHandler twice its already triggered via RegisterNetEvent, also in big code base its save some lines and make easier to find handler that are only for one side (client/server)

`Citizen.Wait instead of Wait` true im talking about things like GetPlayerPed(-1) to PlayerPedId()

`And mixing single quotes and double quotes makes no sense` lua doesnt specify if you need to use single or double quote but for people from other languages is confusing sometimes (https://stackoverflow.com/a/17206437)

Also for changing 'resource:doSomething' to 'resource:client:doSomething' is also to make life easier, if you need to find that one event where is used but you have on client and server event with same name its harder.

**Comment by userMacieG** [comment]
Also I would recomment to change client.lua and server.lua to just main.lua, it doesnt make sense that in folder client you client.lua file like its obvious is file for client, also if you add another file for example vehicle.lua its looks even more weird.
Like in other languages most of the time main file/class is `Main`

**Comment by userMacieG** [comment]
@coalaura ^

**Comment by coalaura** [comment]
This is what i meant when i said i already do it
![yes](https://i.shrt.day/TK352TEDQH.webp)

**Comment by coalaura** [comment]
> Also I would recomment to change client.lua and server.lua to just main.lua, it doesnt make sense that in folder client you client.lua file like its obvious is file for client, also if you add another file for example vehicle.lua its looks even more weird. Like in other languages most of the time main file/class is `Main`

True but in fivem you have a separation between server and client and if you add more script for the client/server side you can put them in the folder. The whole thing is just a boilerplate meant for you to change

**Comment by userMacieG** [comment]
> This is what i meant when i said i already do it ![yes](https://camo.githubusercontent.com/24ff98df1cd7edef66ef6f6bd7b6817541edcb51b933d51b18fa063dff02fbb5/68747470733a2f2f692e736872742e6461792f544b33353254454451482e77656270)

My bad, I was thinking about that: https://manason.github.io/effective-fivem-lua/tables/

**Comment by coalaura** [comment]
All the common things like using different functions i already have checks for. The rest is very much just personal preference and therefore i don't want to force anyone to use it. You're free to use it in your own projects as you please but im not adding it to this extension. Most of the mentioned "good practice" performance gains are very miniscule anyways

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/1VJR6097JM.webp)

from my testing GetHashKey for example is faster than joaat

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/86QEUEMAF8.webp)

Unless you are mass inserting things into a table the performance gain you get from these is negligible. I can look into making an option that highlights these minor performance gains

**Comment by userMacieG** [comment]
> ![yes](https://camo.githubusercontent.com/53276be90045d457ab05d42f3c3bb0e7a33454de046ff56d0c02a9ffb056b970/68747470733a2f2f692e736872742e6461792f31564a52363039374a4d2e77656270)
> 
> from my testing GetHashKey for example is faster than joaat

There was like year ago discussion on overextended discord about that.
If I remember correctly joaat is faster to some point, so over x items its starting to be slower something like that.

edit:
```
joaat is faster with a single call compared to gethashkey, but seems to be alot slower with more iterations
iirc Linden mentioned this with his own benchmarking
```

**Comment by userMacieG** [comment]
https://github.com/coalaura/vs-fivem/blob/main/src/data/ped-config-flags.js
can be updated with data from:
https://alexguirre.github.io/rage-parser-dumps/dump.html?game=gta5&build=3095&search=ePedConfigFlags#ePedConfigFlags

**Comment by coalaura** [comment]
> https://github.com/coalaura/vs-fivem/blob/main/src/data/ped-config-flags.js can be updated with data from: https://alexguirre.github.io/rage-parser-dumps/dump.html?game=gta5&build=3095&search=ePedConfigFlags#ePedConfigFlags

will do, thx. Haven't checked that page in a while, last time that were all that had been found

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/3HMIBE5YHW.webp)
